<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aging Report - {{ $asAtDate->format('d F Y') }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #27ae60;
        }
        .header h1 {
            font-size: 18px;
            margin: 5px 0;
            color: #27ae60;
        }
        .header h3 {
            font-size: 14px;
            margin: 5px 0;
            color: #666;
        }
        .header p {
            margin: 5px 0;
            color: #999;
        }
        .report-title {
            text-align: center;
            font-size: 16px;
            font-weight: bold;
            margin: 20px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        th {
            background: #27ae60;
            color: #fff;
            padding: 8px;
            text-align: left;
            font-size: 11px;
        }
        td {
            padding: 6px 8px;
            border: 1px solid #ddd;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .fw-bold {
            font-weight: bold;
        }
        .bg-light {
            background: #f8f9fa;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #999;
            padding: 10px 0;
            border-top: 1px solid #ddd;
        }
        .page-break {
            page-break-after: always;
        }
        .summary-box {
            background: #f8f9fa;
            padding: 10px;
            margin: 10px 0;
            border-left: 4px solid #27ae60;
        }
        .summary-box h4 {
            margin: 0 0 10px 0;
            color: #27ae60;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>ST. MAXIMILIAN KOLBE COLLEGE</h1>
        <h3>FINANCE CONTROLLER</h3>
        <p>P.O. Box 123, Dar es Salaam, Tanzania | Tel: +255 123 456 789</p>
    </div>

    <div class="report-title">
        ACCOUNTS RECEIVABLE AGING REPORT
    </div>

    <div class="summary-box">
        <h4>Report Summary</h4>
        <table style="width: 50%; margin: 0;">
            <tr>
                <td><strong>As at Date:</strong></td>
                <td>{{ $asAtDate->format('d F Y') }}</td>
            </tr>
            <tr>
                <td><strong>Generated On:</strong></td>
                <td>{{ now()->format('d F Y H:i:s') }}</td>
            </tr>
            <tr>
                <td><strong>Generated By:</strong></td>
                <td>{{ auth()->user()->name ?? 'System' }}</td>
            </tr>
        </table>
    </div>

    <h3>Aging Summary</h3>
    <table>
        <thead>
            <tr>
                <th>Bucket</th>
                <th class="text-right">Count</th>
                <th class="text-right">Amount (TZS)</th>
                <th class="text-right">Percentage</th>
            </tr>
        </thead>
        <tbody>
            @php
                $totalAmount = array_sum(array_column($aging, 'amount'));
            @endphp
            @foreach($aging as $bucket => $data)
            <tr>
                <td>{{ str_replace('_', ' ', ucwords($bucket)) }}</td>
                <td class="text-right">{{ number_format($data['count']) }}</td>
                <td class="text-right">{{ number_format($data['amount'], 2) }}</td>
                <td class="text-right">{{ $totalAmount > 0 ? number_format(($data['amount'] / $totalAmount) * 100, 1) : 0 }}%</td>
            </tr>
            @endforeach
            <tr class="bg-light fw-bold">
                <td>TOTAL</td>
                <td class="text-right">{{ number_format(array_sum(array_column($aging, 'count'))) }}</td>
                <td class="text-right">{{ number_format($totalAmount, 2) }}</td>
                <td class="text-right">100%</td>
            </tr>
        </tbody>
    </table>

    <h3>Aging by Programme</h3>
    <table>
        <thead>
            <tr>
                <th>Programme</th>
                <th class="text-right">Students</th>
                <th class="text-right">Invoices</th>
                <th class="text-right">Current</th>
                <th class="text-right">1-30 Days</th>
                <th class="text-right">31-60 Days</th>
                <th class="text-right">61-90 Days</th>
                <th class="text-right">90+ Days</th>
                <th class="text-right">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($programmeBreakdown as $programme)
            <tr>
                <td>{{ $programme->name }}</td>
                <td class="text-right">{{ $programme->student_count }}</td>
                <td class="text-right">{{ $programme->invoice_count }}</td>
                <td class="text-right">{{ number_format($programme->bucket_1_30, 0) }}</td>
                <td class="text-right">{{ number_format($programme->bucket_31_60, 0) }}</td>
                <td class="text-right">{{ number_format($programme->bucket_61_90, 0) }}</td>
                <td class="text-right">{{ number_format($programme->bucket_90_plus, 0) }}</td>
                <td class="text-right fw-bold">{{ number_format($programme->total_balance, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="page-break"></div>

    <h3>Aging by Invoice Type</h3>
    <table>
        <thead>
            <tr>
                <th>Invoice Type</th>
                <th class="text-right">Count</th>
                <th class="text-right">Current</th>
                <th class="text-right">1-30 Days</th>
                <th class="text-right">31-60 Days</th>
                <th class="text-right">61-90 Days</th>
                <th class="text-right">90+ Days</th>
                <th class="text-right">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($typeBreakdown as $type)
            <tr>
                <td>{{ str_replace('_', ' ', ucwords($type->invoice_type)) }}</td>
                <td class="text-right">{{ $type->count }}</td>
                <td class="text-right">{{ number_format($type->bucket_1_30, 0) }}</td>
                <td class="text-right">{{ number_format($type->bucket_31_60, 0) }}</td>
                <td class="text-right">{{ number_format($type->bucket_61_90, 0) }}</td>
                <td class="text-right">{{ number_format($type->bucket_90_plus, 0) }}</td>
                <td class="text-right fw-bold">{{ number_format($type->total_balance, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <h3>Detailed Aging by Bucket</h3>
    
    @foreach($aging as $bucket => $data)
    <h4>{{ str_replace('_', ' ', ucwords($bucket)) }} ({{ $data['count'] }} invoices - {{ number_format($data['amount'], 2) }})</h4>
    <table>
        <thead>
            <tr>
                <th>Invoice #</th>
                <th>Student</th>
                <th>Reg No</th>
                <th>Type</th>
                <th>Due Date</th>
                <th class="text-right">Days Overdue</th>
                <th class="text-right">Balance</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['invoices'] as $invoice)
            <tr>
                <td>{{ $invoice->invoice_number }}</td>
                <td>{{ $invoice->student->user->first_name ?? '' }} {{ $invoice->student->user->last_name ?? '' }}</td>
                <td>{{ $invoice->student->registration_number ?? '' }}</td>
                <td>{{ str_replace('_', ' ', ucwords($invoice->invoice_type)) }}</td>
                <td>{{ $invoice->due_date->format('d/m/Y') }}</td>
                <td class="text-right">{{ $invoice->due_date->diffInDays(now()) }} days</td>
                <td class="text-right">{{ number_format($invoice->balance, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @if(!$loop->last)
    <div style="margin-bottom: 20px;"></div>
    @endif
    @endforeach

    <div class="footer">
        <p>This is a computer generated report. No signature is required.</p>
        <p>Generated on: {{ now()->format('d F Y H:i:s') }}</p>
    </div>
</body>
</html>